zherr/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from saltstack.views import login_views
from saltstack import server_urls,deploy_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include(server_urls)),
    url(r'^deploy/', include(deploy_urls)),
    url(r'^login/', login_views.Login),
]

saltstack/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Host(models.Model):
    hostname = models.CharField(max_length=32,unique=True,verbose_name="主机名")
    cpu = models.CharField(max_length=32,verbose_name="CPU")
    memory = models.CharField(max_length=32,verbose_name="内存")
    # os_type = ((0,"CentOS"),(1,"RedHat"),(2,"UbanTu"),(3,"SUSE"))
    # os = models.SmallIntegerField(choices=os_type,default=0,verbose_name="操作系统")
    os = models.CharField(max_length=32,default="CentOS",verbose_name="操作系统")
    status = models.BooleanField(default=False,verbose_name="是否在线")

class HostInfo(models.Model):
    cpu_info = models.CharField(max_length=64,verbose_name="CPU信息")
    kernelrelease = models.CharField(max_length=32,verbose_name="内核名称")
    message = models.TextField(max_length=255,null=True,blank=True,verbose_name="备注信息")
    serialnumber = models.CharField(max_length=128,verbose_name="序列号")
    minion_version = models.CharField(max_length=16,verbose_name="Minion版本")
    osrelease = models.CharField(max_length=32,verbose_name="操作系统版本")
    host = models.OneToOneField(to='Host',on_delete=models.CASCADE)


class Disk(models.Model):
    partition = models.CharField(max_length=32,verbose_name="对应分区")
    disk_type = models.CharField(max_length=32,verbose_name="硬盘类型")
    disk_size = models.CharField(max_length=32,verbose_name="硬盘大小")
    hostinfo = models.ForeignKey(to='HostInfo',on_delete=models.CASCADE)

class Network(models.Model):
    ipaddr = models.CharField(max_length=32,verbose_name="IP地址")
    network_name = models.CharField(max_length=32,verbose_name="网卡名称")
    mac_addr = models.CharField(max_length=32,verbose_name="MAC地址")
    bandwidth = models.CharField(max_length=10000,verbose_name="带宽",null=True,blank=True)
    host = models.ForeignKey(to='Host',on_delete=models.CASCADE)

class Room(models.Model):
    region = models.CharField(max_length=64,null=True,blank=True,verbose_name="机房/地区")
    principal = models.CharField(max_length=32,null=True,blank=True,verbose_name="负责人")
    phone = models.CharField(max_length=32,null=True,blank=True,verbose_name="联系方式")
    cabinet = models.CharField(max_length=32,null=True,blank=True,verbose_name="机柜位置")
    room_info = models.OneToOneField(to='HostInfo',on_delete=models.CASCADE)


########################### User

class User(models.Model):
    username = models.CharField(max_length=12,unique=True,verbose_name="用户名")
    passwrod = models.CharField(max_length=24,verbose_name="密码")
    role = models.ForeignKey(to="Role",verbose_name="对应的职位")

    def __str__(self):
        return self.username


class Role(models.Model):
    job = models.CharField(max_length=12,unique=True,verbose_name="职位")
    permission = models.ManyToManyField(to="Permission",blank=True,null=True)

    def __str__(self):
        return self.job


class Permission(models.Model):
    title =  models.CharField(max_length=12,unique=True,verbose_name="标题")
    url =  models.CharField(max_length=64,unique=True,verbose_name="含正则的URL")

    def __str__(self):
        return self.title

saltstack/views/login_views.py
# /usr/bin/python
# -*- coding: utf-8 -*-

from saltstack  import models
from django.shortcuts import render, HttpResponse,redirect


def Login(request):
    if request.method == "GET":
        return render(request,"login.html")
    username = request.POST.get("username")
    password = request.POST.get("password")

    obj = models.User.objects.filter(username=username,passwrod=password).first()
    if obj:
        role = obj.role.job
        # 权限空列表
        permissions_list = []

        per = models.Role.objects.filter(job=role).first()
        permission_qset = per.permission.all()
        for i in permission_qset:
            permissions_list.append(i.url)

        # 将权限信息放到session

        request.session['url'] = permissions_list

        return redirect("/server/index/")

    return render(request, "login.html")

templates/default.html
<div id="areascontent">
    <div class="rows" style="margin-bottom: 0.8%; overflow: hidden;">
        <div style="float: left; width: 69.2%;">
            <div style="height: 100%; border: 1px solid #e6e6e6; overflow: hidden;">
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #578ebe;">
                        <div class="stat-icon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <h2 class="m-top-none">17<span>个</span></h2>
                        <h5>待办未处理</h5>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #e35b5a;">
                        <h2 class="m-top-none">12<span>条</span></h2>
                        <h5>预警信息未读</h5>
                        <div class="stat-icon">
                            <i class="fa fa-bell"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #44b6ae;">
                        <h2 class="m-top-none">20<span>封</span></h2>
                        <h5>邮件未读</h5>
                        <div class="stat-icon">
                            <i class="fa fa-envelope-o"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #8775a7; margin-right: 0px;">
                        <h2 class="m-top-none">6</h2>
                        <h5>对公待签收任务</h5>
                        <div class="stat-icon">
                            <i class="fa fa-gavel"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #4f5c65; margin-bottom: 0px;">
                        <h2 class="m-top-none">324<span>件</span></h2>
                        <h5>今日订单数</h5>
                        <div class="stat-icon">
                            <i class="fa fa-shopping-cart"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #14aae4; margin-bottom: 0px;">
                        <h2 class="m-top-none">525<span>件</span></h2>
                        <h5>昨日订单数</h5>
                        <div class="stat-icon">
                            <i class="fa fa-file-text-o"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item" style="background-color: #949FB1; margin-bottom: 0px;">
                        <h2 class="m-top-none">355<span>件</span></h2>
                        <h5>回退订单数</h5>
                        <div class="stat-icon">
                            <i class="fa fa-coffee"></i>
                        </div>
                    </div>
                </div>
                <div class="dashboard-stats">
                    <div class="dashboard-stats-item"
                         style="background-color: #f29503; margin-right: 0px; margin-bottom: 0px;">
                        <h2 class="m-top-none">3335<span>元</span></h2>
                        <h5>昨日成交金额</h5>
                        <div class="stat-icon">
                            <i class="fa fa-rmb" style="padding-left: 10px;"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="float: right; width: 30%;">
            <div style="height: 221px; border: 1px solid #e6e6e6; background-color: #fff;">
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-area-chart fa-lg" style="padding-right: 5px;"></i>成交订单
                    </div>
                    <div class="panel-body">
                        <canvas id="Canvas2" style="height: 165px; width: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<style>
    #copyrightcontent {
        height: 30px;
        line-height: 29px;
        overflow: hidden;
        position: absolute;
        top: 100%;
        margin-top: -30px;
        width: 100%;
        background-color: #fff;
        border: 1px solid #e6e6e6;
        padding-left: 10px;
        padding-right: 10px;
    }

    .dashboard-stats {
        float: left;
        width: 25%;
    }

    .dashboard-stats-item {
        position: relative;
        overflow: hidden;
        color: #fff;
        cursor: pointer;
        height: 105px;
        margin-right: 10px;
        margin-bottom: 10px;
        padding-left: 15px;
        padding-top: 20px;
    }

    .dashboard-stats-item .m-top-none {
        margin-top: 5px;
    }

    .dashboard-stats-item h2 {
        font-size: 28px;
        font-family: inherit;
        line-height: 1.1;
        font-weight: 500;
        padding-left: 70px;
    }

    .dashboard-stats-item h2 span {
        font-size: 12px;
        padding-left: 5px;
    }

    .dashboard-stats-item h5 {
        font-size: 12px;
        font-family: inherit;
        margin-top: 1px;
        line-height: 1.1;
        padding-left: 70px;
    }

    .dashboard-stats-item .stat-icon {
        position: absolute;
        top: 18px;
        font-size: 50px;
        opacity: .3;
    }

    .dashboard-stats i.fa.stats-icon {
        width: 50px;
        padding: 20px;
        font-size: 50px;
        text-align: center;
        color: #fff;
        height: 50px;
        border-radius: 10px;
    }

    .panel-default {
        border: none;
        border-radius: 0px;
        margin-bottom: 0px;
        box-shadow: none;
        -webkit-box-shadow: none;
    }

    .panel-default > .panel-heading {
        color: #777;
        background-color: #fff;
        border-color: #e6e6e6;
        padding: 10px 10px;
    }

    .panel-default > .panel-body {
        padding: 10px;
        padding-bottom: 0px;
    }

    .panel-default > .panel-body ul {
        overflow: hidden;
        padding: 0;
        margin: 0px;
        margin-top: -5px;
    }

    .panel-default > .panel-body ul li {
        line-height: 27px;
        list-style-type: none;
        white-space: nowrap;
        text-overflow: ellipsis;
    }

    .panel-default > .panel-body ul li .time {
        color: #a1a1a1;
        float: right;
        padding-right: 5px;
    }
</style>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>登录</title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">

      <form class="form-signin" action="" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">欢迎登录RR资产管理平台</h2>
        <label for="inputEmail" class="sr-only">用户名</label>
        <input id="inputUsername" class="form-control" placeholder="用户名" required="" autofocus="" type="text" name="username">
        <label for="inputPassword" class="sr-only">Password</label>
        <input id="inputPassword" class="form-control" placeholder="密码" required="" type="password" name="password">
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
      </form>

    </div> <!-- /container -->

</body>
</html>

templates/network_edit.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> 修改网络信息 </title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">
    <h2>网络修改</h2>

        <form action="" method="post">
            {% csrf_token %}
                <p>
                    {{ net_name }}:<input type="number" class="form-control" name="{{ net_name }}">
                </p>
                <p>
                    <button type="submit" class="btn btn-primary">修改</button>
                </p>
        </form>

</div>

</body>
</html>

templates/room_edit.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> 修改机房信息 </title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">
    <h2>机房信息</h2>

        <form action="" method="post">
            {% csrf_token %}
            <p>
                <input type="text" class="form-control" placeholder="地区/机房" name="region">
            </p>
            <p>
                <input type="text" class="form-control" placeholder="负责人" name="principal">
            </p>
            <p>
                <input type="text" class="form-control" placeholder="联系方式" name="phone">
            </p>
            <p>
                <input type="text" class="form-control" placeholder="机柜位置" name="cabinet">
            </p>

            <p>
                <button type="submit" class="btn btn-primary">添加主机</button>
            </p>
        </form>

</div>

</body>
</html>

templates/server_add.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> 添加主机 </title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container-fluid">
    <h2>添加主机</h2>

        <form action="" method="post">
            {% csrf_token %}
            <p><input type="text" class="form-control" placeholder="请输入主机名" name="host"></p>
            <p>
                <button type="submit" class="btn btn-primary">添加主机</button>
            </p>
        </form>

</div>

</body>
</html>

templates/server_info.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>主机详情</title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 ">

            <div class="panel panel-default">
                <div class="panel-heading">基本信息</div>

                <ul class="list-group">
                    <li class="list-group-item"><b>主机名: </b>{{ host_info.host.hostname }}</li>
                    <li class="list-group-item"><b>操作系统：</b>{{ host_info.host.os }} {{ host_info.osrelease }}</li>
                    <li class="list-group-item"><b>内核版本： </b>{{ host_info.kernelrelease }}</li>
                    <li class="list-group-item"><b>CPU：</b>{{ host_info.cpu_info }}</li>
                    <li class="list-group-item"><b>序列号：</b>{{ host_info.serialnumber }}</li>
                    <li class="list-group-item"><b>Minion版本：</b>{{ host_info.minion_version }}</li>
                    <li class="list-group-item"><b>备注：</b>{{ host_info.message }}</li>
                </ul>
            </div>

        </div>

        <div class="col-md-8 ">
            <div class="panel panel-success">
                <div class="panel-heading">网络信息
                    <a href="/server/network_info_edit/{{ host_info.pk }}/"></a>
                </div>

                <table class="table table-bordered" style="text-align: center">
                    <tr>
                        <th>网卡名称</th>
                        <th>IP地址</th>
                        <th>MAC地址</th>
                        <th>带宽</th>
                    </tr>
                    {% for i in network_info.network_set.all %}
                        <tr>
                            <td>{{ i.network_name }}</td>
                            <td>{{ i.ipaddr }}</td>
                            <td>{{ i.mac_addr }}</td>
                            <td>{{ i.bandwidth }}
                                <a href="/server/network_info_edit/{{ i.id }}/">
                                    <span class="glyphicon glyphicon-pencil pull-right"></span>
                                </a>
                            </td>

                        </tr>
                    {% endfor %}
                </table>
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading">机房信息

                    {% if if_has_permission %}
                        <a href="/server/room_info_edit/{{ host_info.room.pk }}/">
                            <span class="glyphicon glyphicon-pencil pull-right" style="color: white"></span>
                        </a>
                    {% endif %}

                </div>

                <table class="table table-bordered" style="text-align: center">
                    <tr>
                        <th>机房/地区</th>
                        <th>负责人</th>
                        <th>联系方式</th>
                        <th>机柜位置</th>
                    </tr>
                    <tr>
                        <td> {{ host_info.room.region }} </td>
                        <td> {{ host_info.room.principal }} </td>
                        <td> {{ host_info.room.phone }} </td>
                        <td> {{ host_info.room.cabinet }} </td>
                    </tr>

                    {#                    {% for form in formset %}#}
                    {#                        <tr>#}
                    {#                            {% for field in form %}#}
                    {#                                {% if forloop.last %}#}
                    {#隐藏id#}
                    {#                                    <td class="hide">{{ field }}</td>#}
                    {#                                {% else %}#}
                    {#显示其他字段#}
                    {#                                    <td>{{ field }}{{ field.errors.0 }}</td>#}
                    {#                                {% endif %}#}
                    {#                            {% endfor %}#}
                    {##}
                    {#                        </tr>#}
                    {#                    {% endfor %}#}


                </table>
            </div>

        </div>
    </div>


    <div class="row">
        <div class="col-md-4 ">

            <div class="panel panel-info">
                <div class="panel-heading">硬盘信息</div>

                <table class="table table-bordered" style="text-align: center">
                    <tr>
                        <th>对应分区</th>
                        <th>硬盘类型</th>
                        <th>硬盘大小</th>
                    </tr>
                    {% for i in host_info.disk_set.all %}
                        <tr>
                            <td>{{ i.partition }}</td>
                            <td>{{ i.disk_type }}</td>
                            <td>{{ i.disk_size }}</td>
                        </tr>
                    {% endfor %}
                </table>

            </div>

        </div>

    </div>
</div>

</body>
</html>

templates/server_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>主机详情</title>
    <link href="/static/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <h2>主机列表</h2>
    </div>

    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <table class="table table-bordered table-striped dataTable" style="text-align: center">
                    <tr>
                        <th>ID</th>
                        <th>主机名</th>
                        <th>操作系统</th>
                        <th>CPU</th>
                        <th>内存</th>
                        <th>IP地址</th>
                        <th>状态</th>
                    </tr>
                    {% for i in current_list %}
                        <tr>
                            <td>{{ i.id }}</td>
                            <td><a href="/server/list/info/{{ i.id }}/">{{ i.hostname }}</a></td>
                            <td>{{ i.os }}</td>
                            <td>{{ i.cpu }}</td>
                            <td>{{ i.memory }} MB</td>
                            <td>
                                {% for n in i.network_set.all %}
                                    {{ n.ipaddr }}<br/>
                                {% endfor %}
                            </td>
                            <td> {% if i.status %}
                                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true" style="color: #43e73a"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-remove-sign" aria-hidden="true" style="color: red"></span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>


            <nav aria-label="Page navigation">
                <ul class="pagination">

                    {#has_previous 判断是否有上一页#}
                    {% if current_list.has_previous %}
                        {#previous_page_number 上一页的页码#}
                        <li><a href="?page={{ current_list.previous_page_number }}" aria-label="Previous"><span
                                aria-hidden="true">上一页</span></a></li>
                    {% else %}
                        {#class="disabled" 禁止用户点击#}
                        <li class="disabled"><a href="" aria-label="Previous"><span aria-hidden="true">上一页</span></a>
                        </li>
                    {% endif %}


                    {#遍历页码的列表#}
                    {% for i in paginator.page_range %}
                        {#判断当前页码数等于底部页码时#}
                        {% if current_num == i %}
                            {#增加class,加深按钮#}
                            <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% else %}
                            {#href参数为简写,它会自动获取当前路径，并拼接参数#}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}


                    {#has_next 判断是否有下一页#}
                    {% if current_list.has_next %}
                        {#next_page_number 下一页的页码#}
                        <li><a href="?page={{ current_list.next_page_number }}" aria-label="Next"><span
                                aria-hidden="true">下一页</span></a></li>
                    {% else %}
                        {#class="disabled" 禁止用户点击#}
                        <li class="disabled"><a href="" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                    {% endif %}


                </ul>
            </nav>


        </div>
    </div>
</div>
</body>
</html>